import React, { useEffect, useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { Shell } from './components/layout/Shell';

// Pages
import Dashboard from './pages/Dashboard';
import Monitoring from './pages/Monitoring';
import Students from './pages/Students';
import Register from './pages/Register';

const Reports = () => (
  <div className="p-space max-w-[1400px] mx-auto">
    <header className="mb-10">
      <h1 className="text-3xl font-bold tracking-tight mb-2">Automated AI Perspectives</h1>
      <p className="text-[var(--secondary)] text-sm">Deep analytics and pattern recognition reports generated by local neural models.</p>
    </header>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div className="p-12 border-2 border-dashed border-[var(--border)] rounded-3xl flex flex-col items-center justify-center text-center">
        <div className="w-16 h-16 bg-[#f9fafb] rounded-full flex items-center justify-center mb-4">
          <div className="w-8 h-8 rounded-full border-4 border-[var(--primary)] border-t-transparent animate-spin" />
        </div>
        <p className="text-lg font-bold text-[var(--foreground)]">Aggregating Local Data</p>
        <p className="text-sm text-[var(--secondary)] mt-1">Refining intelligence reports. This usually takes 5-10 seconds.</p>
      </div>
    </div>
  </div>
);

export default function App() {
  return (
    <Router>
      <Shell>
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/monitoring" element={<Monitoring />} />
          <Route path="/students" element={<Students />} />
          <Route path="/enrollment" element={<Register />} />
          <Route path="/reports" element={<Reports />} />
        </Routes>
      </Shell>
    </Router>
  );
}
